brain/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount LeaguebotApi => '/api'

  get 'event', to: "application#index"
  get 'kartalytics_matches/:id', as: 'kartalytics_match', to: 'application#index'
  get 'leaderboard', to: "application#index"

  get 'players', to: "application#index"
  get 'players/:name', to: "application#index"

  get 'courses', to: "application#index"
  get 'courses/:name', to: "application#index"

  get 'edit_current_race', to: "application#edit_current_race"
  post 'update_current_race', to: "application#update_current_race"

  get 'kartalytics_races/audit', to: 'kartalytics_races#audit'
  patch 'kartalytics_races/:id', as: 'update_kartalytics_race', to: 'kartalytics_races#update'

  root 'application#index'
end

brain/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    render html: '', layout: true
  end

  def edit_current_race
    @courses = KartalyticsCourse.all.order(name: :asc)
    render :edit_current_race, layout: false
  end

  def update_current_race
    course = KartalyticsCourse.find_by(name: params[:course])
    KartalyticsState.instance.current_race&.update(course: course)

    redirect_to edit_current_race_path
  end
end

brain/app/views/application/edit_current_race.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kartalytics</title>
  <meta name="viewport" content="width=device-width">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <style type="text/css">
    * {
      box-sizing: border-box;
    }

    form {
      margin: 0 auto;
      max-width: 375px;
    }

    input, select, button {
      display: block;
      font-size: 16px;
      margin: 0.5rem 0;
      padding: 0.5rem;
      width: 100%;
    }

    button {
      height: 8rem;
    }
  </style>
</head>
<body>
  <%= form_with url: update_current_race_path, method: :post, local: true do |form| %>
    <input id="search" placeholder="search" autofocus />
    <%= form.select :course, @courses.map(&:name) %>
    <%= form.button "submit" %>
  <% end %>

  <script>
    document.querySelector('#search').addEventListener('input', (event) => {
      const option = Array.from(document.querySelectorAll('#course option')).find(option => {
        return new RegExp(event.target.value, 'i').test(option.label);
      });

      if (option) document.querySelector('#course').value = option.value;
    });
  </script>
</body>
</html>